[package]
name = "postgres-with-rust"
version = "0.1.0"
authors = ["PankajChaudhary5 <pankajchaudhary172@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.17.5"